#!/bin/bash

BACKUP_PROG=/usr/pgsql-9.6/bin/pg_basebackup
BACKUP_DIR=/mnt/BACKUPS/1c-backup
PGSQL_DATA=/var/lib/pgsql/9.6/data

if [ -f $BACKUP_DIR/$1 ]; then
   echo "Found backup file: " $BACKUP_DIR/$1 ". Restore..."
else
   echo "Not found file to restore:" $BACKUP_DIR/$1 ". Exitting..."
   exit
fi   

service postgresql-9.6 stop
#$BACKUP_PROG -x --format=tar -z -U postgres -D - | tee > $BACKUP_DIR/rest_backup_$(date +%Y-%m-%d_%H:%M).tar.gz
tar czf $BACKUP_DIR/rest_backup_manual_$(date +%Y-%m-%d_%H:%M).tar.gz $PGSQL_DATA
rm -rf $PGSQL_DATA
mkdir $PGSQL_DATA
cd $PGSQL_DATA
tar xzf $BACKUP_DIR/$1
cd ..
chown -R postgres:postgres data
chmod -R 700 data
service postgresql-9.6 start

